### ISSUE TITLE
Installation request for greenpacket/kiplepay ^1.0 -> satisfiable by greenpacket/kiplepay[v1.0.0].

### ISSUE THREAD

**Issue by msquareM** [m2c/kiplepay-php-sdk#1]
when i run this command "composer require greenpacket/kiplepay".
throw below error "
Problem 1
    - Installation request for greenpacket/kiplepay ^1.0 -> satisfiable by greenpacket/kiplepay[v1.0.0].
    - Conclusion: remove symfony/event-dispatcher v2.8.52
    - Conclusion: don't install symfony/event-dispatcher v2.8.52
    - greenpacket/kiplepay v1.0.0 requires symfony/event-dispatcher ^4.0 -> satisfiable by symfony/event-dispatcher[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].
"
language:php (laravel framework)

**Comment by evans191014** [comment]
Could you provide a version of you used  laravel framework? Thanks

**Comment by msquareM** [comment]
Hi Evans,
   Thanks for your reply and my laravel version is 5.5
Regards
Mani

**Comment by evans191014** [comment]
Hi Mani,
     Thanks for your suggestion.I fixed this problem and now supports 2.8

**Comment by msquareM** [comment]
Hi Evans,
           Now throw error like below
Problem 1
    - Conclusion: don't install greenpacket/kiplepay v1.0.1
    - Installation request for symfony/http-foundation (locked at v3.4.37) -> satisfiable by symfony/http-foundation[v3.4.37].
    - Conclusion: remove symfony/event-dispatcher v2.8.52
    - Installation request for greenpacket/kiplepay ^1.0 -> satisfiable by greenpacket/kiplepay[v1.0.0, v1.0.1].
    - Conclusion: don't install symfony/event-dispatcher v2.8.52
    - greenpacket/kiplepay v1.0.0 requires symfony/event-dispatcher ^4.0 -> satisfiable by symfony/event-dispatcher[4.0.x-dev, 4.1.x-dev, 4.2.x-dev, 4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1, v4.0.0-BETA2, v4.0.0-BETA3, v4.0.0-BETA4, v4.0.0-RC1, v4.0.0-RC2, v4.0.1, v4.0.10, v4.0.11, v4.0.12, v4.0.13, v4.0.14, v4.0.15, v4.0.2, v4.0.3, v4.0.4, v4.0.5, v4.0.6, v4.0.7, v4.0.8, v4.0.9, v4.1.0, v4.1.0-BETA1, v4.1.0-BETA2, v4.1.0-BETA3, v4.1.1, v4.1.10, v4.1.11, v4.1.12, v4.1.2, v4.1.3, v4.1.4, v4.1.5, v4.1.6, v4.1.7, v4.1.8, v4.1.9, v4.2.0, v4.2.0-BETA1, v4.2.0-BETA2, v4.2.0-RC1, v4.2.1, v4.2.10, v4.2.11, v4.2.12, v4.2.2, v4.2.3, v4.2.4, v4.2.5, v4.2.6, v4.2.7, v4.2.8, v4.2.9, v4.3.0, v4.3.0-BETA1, v4.3.0-BETA2, v4.3.0-RC1, v4.3.1, v4.3.10, v4.3.11, v4.3.2, v4.3.3, v4.3.4, v4.3.5, v4.3.6, v4.3.7, v4.3.8, v4.3.9, v4.4.0, v4.4.0-BETA1, v4.4.0-BETA2, v4.4.0-RC1, v4.4.1, v4.4.10, v4.4.11, v4.4.2, v4.4.3, v4.4.4, v4.4.5, v4.4.6, v4.4.7, v4.4.8, v4.4.9].

**Comment by msquareM** [comment]
Hi Evans,
    Thanks for your email. u fixed the problem but when i run composer like
this command *composer require greenpacket/kiplepay -vvv *through error
like below

- Conclusion: don't install greenpacket/kiplepay v1.0.1
- Installation request for symfony/http-foundation (locked at v3.4.37) ->
satisfiable by symfony/http-foundation[v3.4.37].
- Conclusion: remove symfony/event-dispatcher v2.8.52
- Installation request for greenpacket/kiplepay ^1.0 -> satisfiable by
greenpacket/kiplepay[v1.0.0, v1.0.1].
- Conclusion: don't install symfony/event-dispatcher v2.8.52
- greenpacket/kiplepay v1.0.0 requires symfony/event-dispatcher ^4.0 ->
satisfiable by symfony/event-dispatcher[4.0.x-dev, 4.1.x-dev, 4.2.x-dev,
4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1

*my doubt is how to get version 2.8 through composer .Please give any idea
about this*

*Regards*
*Mani*

**Comment by msquareM** [comment]
Hi Evans,
    Thanks for your email. u fixed the problem but when i run composer like
this command *composer require greenpacket/kiplepay -vvv *throw error like
below

- Conclusion: don't install greenpacket/kiplepay v1.0.1
- Installation request for symfony/http-foundation (locked at v3.4.37) ->
satisfiable by symfony/http-foundation[v3.4.37].
- Conclusion: remove symfony/event-dispatcher v2.8.52
- Installation request for greenpacket/kiplepay ^1.0 -> satisfiable by
greenpacket/kiplepay[v1.0.0, v1.0.1].
- Conclusion: don't install symfony/event-dispatcher v2.8.52
- greenpacket/kiplepay v1.0.0 requires symfony/event-dispatcher ^4.0 ->
satisfiable by symfony/event-dispatcher[4.0.x-dev, 4.1.x-dev, 4.2.x-dev,
4.3.x-dev, 4.4.x-dev, v4.0.0, v4.0.0-BETA1

*my doubt is how to get version 2.8 through composer .Please give any idea
about this*

*Regards*
*Mani*

**Comment by evans191014** [comment]
Hi Mani,
    maybe you can try these steps:
   1. composer remove greenpacket/kiplepay
   2. composer clean
   3. composer require greenpacket/kiplepay
if you have any questions, you can via e-mail for me `evans.yang@greenpacket.com.cn`.  I will deal with it in time.
